### PR TITLE
Lint cleanup: fix all stylecheck violations

### LINKED ISSUE #560: Lint cleanup: stylecheck
Fix all `stylecheck` violations reported by golangci-lint.

Violations fall into three categories:

- **ST1003** (naming): Rename `Id` → `ID`, `CheckCanastaId` → `CheckCanastaID`, `WikiUrlExists` → `WikiURLExists`, and various local variables (`snapshotId`, `parsedUrl`, `normalizedId`, `launchJsonPath`, `phpXmlContent`, `phpXmlPath`) to follow Go naming conventions for acronyms and initialisms.
- **ST1005** (error strings): Lowercase error strings per Go convention.
- **ST1008** (return order): Change `execute.Run` return type from `(error, string)` to `(string, error)` per Go convention that error should be the last return value.

Part of #542.

### PR DESCRIPTION
**Pull request by cicalese**
Fix all `stylecheck` violations reported by golangci-lint across 43 files.

**ST1003 — naming conventions (12 unique violations):**
- Rename struct fields `Id` → `ID` in `Installation`, `Orchestrator`, `CanastaVariables` and all usage (70 occurrences, 21 files)
- Rename `CheckCanastaId` → `CheckCanastaID` (19 files)
- Rename `WikiUrlExists` → `WikiURLExists` (3 files)
- Rename local variables: `snapshotId` → `snapshotID`, `parsedUrl` → `parsedURL`, `normalizedId` → `normalizedID`, `launchJsonPath` → `launchJSONPath`, `phpXmlContent` → `phpXMLContent`, `phpXmlPath` → `phpXMLPath`

**ST1005 — error string capitalization (6 unique violations):**
- Lowercase all capitalized error strings per Go convention

**ST1008 — error return order (2 unique violations):**
- Change `execute.Run` return type from `(error, string)` to `(string, error)` and update all 57 call sites plus 1 test mock

Note: The `json:"id"` struct tag is preserved, so serialization/deserialization of `conf.json` is unaffected.

Fixes #560
Part of #542

### CODE REVIEW

File: internal/imagebuild/imagebuild.go [hunk 1]
```diff
@@ -27,13 +27,13 @@ func BuildFromSource(workspacePath string) (string, error) {
...
 	if _, err := os.Stat(canastaPath); os.IsNotExist(err) {
-		return "", fmt.Errorf("Canasta/ directory not found in %s", workspacePath)
+		return "", fmt.Errorf("canasta/ directory not found in %s", workspacePath)
 	}
 
 	// Check if Canasta has a Dockerfile
 	canastaDockerfile := filepath.Join(canastaPath, "Dockerfile")
 	if _, err := os.Stat(canastaDockerfile); os.IsNotExist(err) {
-		return "", fmt.Errorf("Dockerfile not found in Canasta repo at %s", canastaDockerfile)
+		return "", fmt.Errorf("dockerfile not found in Canasta repo at %s", canastaDockerfile)
```
Comment (yaronkoren) [inline internal/imagebuild/imagebuild.go]: Extremely minor, but this one *should* be capitalized, no?

Comment (cicalese) [reply internal/imagebuild/imagebuild.go]: Good catch! I will fix that.

Comment (cicalese) [reply internal/imagebuild/imagebuild.go]: Fixed!

**Review by yaronkoren — APPROVED** [review]

**Review by yaronkoren — APPROVED** [review]

**Comment by yaronkoren** [comment]
This looks great! I do prefer "ID" and "URL" in variable names.
