### PR TITLE
Delete installation on failure

### LINKED ISSUE #14: When canasta has failed, but created directories for an install, it can't run again against the same `create` without error
Example:
```
$ ls -l test
total 24
drwxr-xr-x. 3 root root   86 Aug 19 01:15 config
-rw-r--r--. 1 root root  545 Aug 19 01:15 docker-compose.override.yml
...
$ sudo ./Canasta-CLI-Go create
Enter Wiki Name: test
Enter Canasta ID: test
Enter admin name: test
Enter the admin password (Press Enter to autogenerate the password): 
Setting up Canasta
fatal: destination path '/home/mah/Canasta-CLI/test' already exists and is not an empty directory.
$

### PR DESCRIPTION
**Pull request by amalpaul54111**
Fixes #14
So when a create/import command fails, `canasta` CLI asks the user whether to keep the config files or not.

### CODE REVIEW

**Comment by hexmode** [comment]
Tested.

Looks pretty good to me.  I would prefer a CLI option to keep and then change the default to delete, but if @jeffw16 or @yaronkoren like this implementation, it works.

**Comment by yaronkoren** [comment]
@hexmode - great!

I think this is good - even if the plan is to add a "keep on failure" option, this is a step in the right direction anyway. (A big step.)

**Comment by jeffw16** [comment]
I agree with @hexmode: it should be delete by default.

File: cmd/create/create.go [hunk 1]
```diff
@@ -30,8 +32,19 @@ func NewCmdCreate() *cobra.Command {
...
 			fmt.Println("Setting up Canasta")
 			if err = createCanasta(canastaInfo, pwd, path, orchestrator); err != nil {
-				orchestrators.Delete(path, orchestrator)
-				logging.Fatal(err)
+				fmt.Print(err.Error(), "\n")
+				fmt.Println("A fatal error occured during the installation\nDo you want to delete the files related to it? (y/n)")
+				scanner := bufio.NewScanner(os.Stdin)
+				scanner.Scan()
+				input := scanner.Text()
+				if input == "y" {
```
Comment (jeffw16) [inline cmd/create/create.go]: Please change to delete by default, keep only by explicit request

**Review by jeffw16 — CHANGES_REQUESTED** [review]

File: cmd/create/create.go (hunk 1 above)
Comment (jeffw16) [reply cmd/create/create.go]: Also I'm pretty sure we can do better than simply checking for a lowercase `y` or `n`. There's more possible cases, such as `yes` or `no` or `Y` or `N`.

Comment (amalpaul54111) [reply cmd/create/create.go]: > Also I'm pretty sure we can do better than simply checking for a lowercase `y` or `n`. There's more possible cases, such as `yes` or `no` or `Y` or `N`.

Yeah, sure. 

> Please change to delete by default, keep only by explicit request

Okay, also should there be a CLI option to keep the files, so it does not prompt?

Comment (yaronkoren) [reply cmd/create/create.go]: I would say, in the interests of time (and keeping this patch manageable), don't worry about adding an option to keep the files - it would be nice to have, but it can always be added later.

Comment (jeffw16) [reply cmd/create/create.go]: I agree with @yaronkoren

**Review by jeffw16 — APPROVED** [review]
