### PR TITLE
Use environment variables and new config directory structure

### LINKED ISSUE #157: canasta create --database fails with 'There is no LocalSettings.php' error
### Description

When creating a new Canasta installation by importing an existing database dump using `canasta create --database`, the wiki fails to start with the error:

```
There is no LocalSettings.php/CommonSettings.php file
```

### Steps to Reproduce

1. Export a database from an existing MediaWiki installation
2. Run: `canasta create -i mywiki -w wiki1 -n example.com --database backup.sql`
3. Try to access the wiki

### Expected Behavior

The wiki should start and be accessible using the imported database.

### Actual Behavior

The web container shows the error "There is no LocalSettings.php/CommonSettings.php file" and the wiki is inaccessible.

### Root Cause

When `--database` is provided, the CLI skips running `install.php` (since we're importing an existing database, not creating a new one). However, `install.php` is what normally generates `LocalSettings.php`. Without this file, MediaWiki won't start.

### Proposed Solution

Instead of generating a `config/LocalSettings.php` file, move the essential settings to environment variables:

1. Database password: Already in `.env` as `MYSQL_PASSWORD`
2. Secret key: Generate and save to `.env` as `MW_SECRET_KEY`

`CanastaDefaultSettings.php` in the Docker image will read these environment variables directly. No `config/LocalSettings.php` is needed.

This approach:
- Works for both fresh installs and database imports
- Eliminates confusion from having two files named LocalSettings.php
- Keeps `config/` directory clean (only user-editable files)

### Backward Compatibility

This is a new feature (`--database` flag), so there are no existing installations using it. However, the solution requires updates to the Docker image (`CanastaDefaultSettings.php`) to read from environment variables.

Existing installations will continue to work because:
- `CanastaDefaultSettings.php` still loads `config/LocalSettings.php` if it exists
- The env var values are only used as defaults, overridden by any existing `config/LocalSettings.php`

### Related

- Depends on CanastaWiki/CanastaBase#57
- Depends on CanastaWiki/CanastaBase#58
- Related to #159

### PR DESCRIPTION
**Pull request by cicalese**
## Summary

- Replace `GenerateLocalSettings()` with `GenerateAndSaveSecretKey()`
- Save `MW_SECRET_KEY` to `.env` instead of creating `config/LocalSettings.php`
- Delete installer-generated `LocalSettings.php` after installation
- Remove `CommonSettings.php` vs `LocalSettings.php` distinction (all installations are wiki farms)
- Replace `SettingsTemplate.php` with generated README files
- Update directory paths:
  - Global settings: `config/settings/global/`
  - Per-wiki settings: `config/settings/wikis/<wiki_id>/`
- Remove unused `LocalSettingsTemplate.php`

**Fixes `canasta create --database` failing:** Previously, when importing a database dump with `--database`, the CLI skipped `install.php` (which normally generates `config/LocalSettings.php`), causing MediaWiki to fail with "There is no LocalSettings.php/CommonSettings.php file". This PR eliminates the need for `config/LocalSettings.php` entirely by using environment variables (`MW_SECRET_KEY`, `MYSQL_PASSWORD`) instead.

## Issues

Fixes #157, #158, #159

## Related PRs

- CanastaWiki/CanastaBase#59 - Environment variable support and directory structure
- CanastaWiki/Canasta#573 - Update BASE_IMAGE to canasta-base:1.0.8
- CanastaWiki/Canasta-DockerCompose#77 - Remove SettingsTemplate.php, add numeric prefixes to settings files

## Merge Order

1. **CanastaBase #59** - merge first
2. Wait for `canasta-base:1.0.8` image to build
3. **Canasta #573** - update BASE_IMAGE
4. Wait for `canasta:latest` image to build
5. **Canasta-DockerCompose #77**
6. **Canasta-CLI #161** (this PR) - merge last

## Test plan

- [x] Verify `canasta create -i test -w mywiki -n localhost --admin Admin` works (fresh wiki)
- [x] Verify `canasta create -i test -w mywiki -n localhost --database dump.sql` works (imported wiki)
- [x] Verify `MW_SECRET_KEY` is saved to `.env`
- [x] Verify `config/LocalSettings.php` is NOT created
- [x] Verify wiki settings are created in `config/settings/wikis/<wiki_id>/`
- [x] Verify README files are generated with correct content
- [x] Verify existing installations continue to work

### CODE REVIEW

**Review by jeffw16 — APPROVED** [review]

File: internal/mediawiki/mediawiki.go [hunk 1]
```diff
@@ -52,21 +53,29 @@ func Install(path, yamlPath, orchestrator string, canastaInfo canasta.CanastaVar
...
 		}
 		time.Sleep(time.Second)
 	}
 
-	// Generate secret key and save to .env (DB password already in .env)
-	// No config/LocalSettings.php is created - CanastaDefaultSettings.php reads from env vars
-	if err := canasta.GenerateAndSaveSecretKey(path); err != nil {
-		return canastaInfo, err
+	if len(WikiIDs) == 1 {
+		settingsName = "LocalSettings.php"
```
Comment (jeffw16) [inline internal/mediawiki/mediawiki.go]: Nit: Might be better to make a const for `LocalSettings.php`, `LocalSettingsBackup.php`, and `CommonSettings.php` variables

**Review by jeffw16 — APPROVED** [review]

**Review by yaronkoren — APPROVED** [review]
