### PR TITLE
Fix upgrade recreating deleted files and Caddyfile.custom migration

### LINKED ISSUE #517: Upgrade recreates deleted files and fails to migrate Caddyfile.custom
## Problems

Two issues found during real-world upgrade from a pre-v1.107.0 installation:

### 1. Caddy restart loop after upgrade

After `canasta upgrade`, Caddy enters a restart loop with:
```
Error: adapting config using caddyfile: File to import not found: /etc/caddy/Caddyfile.custom
```

The Caddyfile still references the old `Caddyfile.custom` name (renamed to `Caddyfile.site` in #297). The migration in `migrateCaddyFiles()` only checks whether `Caddyfile.site` and `Caddyfile.global` exist — it doesn't check whether the Caddyfile itself still references the old name. Since `UpdateStackFiles` creates `Caddyfile.site` from the template before migrations run, the migration thinks everything is fine.

### 2. Upgrade recreates user-deleted files

`Vector.php` and `CanastaFooterIcon.php` are recreated by `UpdateInstallationTemplate()` during upgrade, even if the user intentionally deleted them. The current no-clobber logic only skips if the file exists — it recreates missing files.

## Expected behavior

1. The migration should rename `Caddyfile.custom` → `Caddyfile.site` and rewrite the Caddyfile if it references the old name.
2. User-editable template files should be skipped entirely during upgrade.

### PR DESCRIPTION
**Pull request by cicalese**
## Summary
- Handle `Caddyfile.custom` → `Caddyfile.site` rename during upgrade migration: rename the old file, detect stale references in the Caddyfile, and rewrite it
- Skip user-editable template files entirely during upgrade so intentionally deleted files (e.g., `Vector.php`, `CanastaFooterIcon.php`) are not recreated

## Context
Found during real-world upgrade from a pre-v1.107.0 installation. After upgrade, Caddy entered a restart loop because the Caddyfile still imported `Caddyfile.custom`. Separately, `Vector.php` and `CanastaFooterIcon.php` were recreated despite having been intentionally removed.

Fixes #517

### CODE REVIEW

File: internal/canasta/canasta.go [hunk 1]
```diff
@@ -78,16 +78,16 @@ func CopyInstallationTemplate(destPath string) error {
...
 func UpdateInstallationTemplate(destPath string) error {
 	logging.Print("Updating installation template files\n")
 	return copyTemplate(destPath, true)
 }
 
 // copyTemplate walks the embedded installation template and copies files to destPath.
-// If upgrading is true, CLI-managed files are force-updated while user-editable files
-// use no-clobber. If upgrading is false, all files use no-clobber.
+// If upgrading is true, CLI-managed files are force-updated and user-editable files
+// are skipped. If upgrading is false (create), all files use no-clobber.
```
Comment (yaronkoren) [inline internal/canasta/canasta.go:90]: Shouldn't this also change to "are skipped"?

Comment (yaronkoren) [reply internal/canasta/canasta.go:90]: The second "use no-clobber", that is.

Comment (cicalese) [reply internal/canasta/canasta.go:90]: It does — see lines 89-90 in the diff. The comment changed from "use no-clobber" to "are skipped".

Comment (yaronkoren) [reply internal/canasta/canasta.go:90]: The second "use no-clobber".

Comment (cicalese) [reply internal/canasta/canasta.go:90]: Correct. No-clobber is correct for create.

Comment (yaronkoren) [reply internal/canasta/canasta.go:90]: I'm not sure you understood what I meant, but... it hardly matters.

**Review by yaronkoren — APPROVED** [review]

File: internal/canasta/canasta.go (hunk 1 above)
Comment (cicalese) [reply internal/canasta/canasta.go:90]: Maybe not. Are you talking about the 'no-clobber' on line 90? Or the one on line 126? Both of them are create behavior, which is no-clobber. Other than that, I'm not sure what you meant.
