### PR TITLE
Move password length validation to pre-create stage

### LINKED ISSUE #373: New wiki setup wizard accepts password less than 10 characters
Steps to reproduce
1. Follow the "Installation" and "Create new wiki" steps at http://canasta.wiki/setup/ for CLI installation
2. Enter a password less than 10 characters when prompted

What happens: The wizard accepts the input, attempts the installation, and then fails due to the lack of a 10-character password

What should happen: The wizard ideally would reject invalid passwords (at the very least, passwords <10 characters) and not proceed until a valid password is entered.

### PR DESCRIPTION
**Pull request by naresh-kumar-babu**
Fixes https://github.com/CanastaWiki/Canasta/issues/373

### CODE REVIEW

File: internal/prompt/prompt.go [hunk 1]
```diff
@@ -125,6 +125,11 @@ func getAndConfirmPassword(username string) (string, string, error) {
 	if err != nil || password != confirmedPassword {
 		return "", "", fmt.Errorf("Passwords do not match, please try again.")
 	}
+	if len(password) < 10 {
```
Comment (jeffw16) [inline internal/prompt/prompt.go]: Why did we move this away from its own function? This makes it less unit testable.

**Review by jeffw16 — CHANGES_REQUESTED** [review]

**Comment by jeffw16** [comment]
Can we write some unit tests to ensure this function works correctly?

**Comment by naresh-kumar-babu** [comment]
> Can we write some unit tests to ensure this function works correctly?

Added unit test.

**Review by jeffw16 — APPROVED** [review]
